rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
bundler_args: --without development
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'
notifications:
  irc: "irc.freenode.org#travis"
